### ISSUE TITLE
31º encontro do GruPy Blumenau - 17/06/2023

### ISSUE THREAD

**Issue by rtancman** [pythonbnu/meetups#3]
### Data do encontro

17 de junho de 2023

### Local do encontro

FURB Campus 1, Bloco S, Sala s410

---

Submeta aqui a sua palestra para o encontro, nos comentários desta issue. Use o seguinte layout no seu comentário:

```md
**Título da palestra**
**Descrição**: seja breve
**Categoria:** digite quantas quiser separadas por vírgula
**Dificuldade:** escolha entre as opções listadas abaixo
```

### Exemplo de dica

**Programação assíncrona com FastAPI**
**Descrição:** Irei abordar técnicas de como criar APIs REST, utilizando as melhores práticas e ferramentas que o asyncio, e o FastAPI nos ofertam, como as famosas Background Tasks.
**Categoria:** Python, FastAPI, asyncio, Programação Assíncrona
**Dificuldade:** Intermediário

#### Categoria:

Em qual contexto a sua talk mais se encaixa?

Alguns dos exemplos de categorias mais usadas: `python`, `django`, `fastapi`, `flask`, `celery`, `kubernetes`, `linux`, `orm`, `programação assíncrona`.

#### Dificuldade:

Tente se colocar no lugar do seu público e escolha a melhor categoria que sua palestra pode se encaixar: `Iniciante`, `Intermediário`, `Avançado`.

---

**Iremos fechar essa issue dia 07/06/23 às 19:00 PM**. As mais votadas serão selecionadas para a próxima edição do **GruPy Blumenau**.

**Comment by jjpaulo2** [comment]
**FastAPI na prática: Criando uma API RESTful do zero**

**Descrição**: Entenderemos alguns conceitos de HTTP e REST. Faremos um CRUD usando FastAPI, e mostraremos algumas das features mais legais do framework, como Background Tasks e injeção de dependências nos endpoints.
**Categoria:** `fastapi`, `apis`, `rest`, `crud`
**Dificuldade:** iniciante

**Comment by jjpaulo2** [comment]
Evento realizado com sucesso.
